file_format: "1"
id: arkenswoop
name: arkenswoop/Sweep
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - encoder
siblings:
  - arkenswoop_left
  - arkenswoop_right
