on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@0755b7a64c39736f6235ac0403e752692d367400
